language: cpp

os: [linux, osx]
compiler: [gcc, clang]

addons:
  apt:
    packages: [cmake, gcc-multilib, g++-multilib, valgrind]
    sources: [ubuntu-toolchain-r-test]

env:
  matrix:
    - BUILD_TYPE=Debug   CFLAGS=-m32 CXXFLAGS=-m32
    - BUILD_TYPE=Debug   CFLAGS=-m64 CXXFLAGS=-m64
    - BUILD_TYPE=Release CFLAGS=-m32 CXXFLAGS=-m32
    - BUILD_TYPE=Release CFLAGS=-m64 CXXFLAGS=-m64

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
      CMAKE_PACKAGE="cmake-3.3.2-Linux-x86_64"
      mkdir cmake
      wget https://cmake.org/files/v3.3/${CMAKE_PACKAGE}.tar.gz --no-check-certificate --quiet | tar --strip-components=1 -xz -C cmake
      export PATH=`pwd`/cmake/bin:${PATH}
    else
      brew update
      brew unlink cmake
      brew install -v cmake
    fi

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DASMJIT_BUILD_TEST=1
  - cd ..

script:
  - cd build
  - make
  - cd ..

  - ./build/asmjit_test_unit
  - ./build/asmjit_test_opcode > /dev/null
  - ./build/asmjit_test_x86_asm
  - ./build/asmjit_test_x86_cc

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_unit; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_x86_asm; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_x86_cc; fi;
